### ISSUE TITLE
Responsive issues in mobile

### ISSUE THREAD

**Issue by anshad** [asitparida/PieMix#18]
The chart getting hidden behind the screen as the line is taking more space. It should check for mobile screen and render the legends next row after the chart.

**Comment by asitparida** [comment]
For now, try using <config>.showLabels = false to hide the labels. Adding the item to future scope wherein we design how to display the labels when in mobile resolutions.

**Comment by asitparida** [comment]
The plugin should not handle how the legends should look in mobile view. Have added two extensions to simulate hover on pie on click from labels.Please use this. Another task would be taken up later to auto set <CONFIG>.showLabels to false when screen goes below 768 px.
